// This file is generated by scripts/sync-template-config.mjs.
// Do not edit it manually.

import { APP_BRAND } from "../brand/brand";

export type ThemeMode = "system" | "light" | "dark";

export interface ShellSettings {
  theme: ThemeMode;
  startMinimized: boolean;
}

export const defaultShellSettings: ShellSettings = {
  theme: "system",
  startMinimized: false,
};

export const SETTINGS_STORAGE_KEY = `${APP_BRAND.packageName}.settings`;
export const THEME_STORAGE_KEY = `${APP_BRAND.packageName}.theme`;
