// This file is generated by scripts/sync-template-config.mjs.
// Do not edit it manually.

import { TEMPLATE_CONFIG } from "./templateConfig";

export const APP_BRAND = {
  displayName: TEMPLATE_CONFIG.appName,
  packageName: TEMPLATE_CONFIG.packageName,
  productName: TEMPLATE_CONFIG.productName,
  description: TEMPLATE_CONFIG.description,
  repositoryUrl: TEMPLATE_CONFIG.repositoryUrl,
  windowTitle: TEMPLATE_CONFIG.productName,
  identifier: TEMPLATE_CONFIG.identifier,
  deepLinkScheme: TEMPLATE_CONFIG.deepLinkScheme,
  updaterEndpoint: TEMPLATE_CONFIG.updaterEndpoint,
} as const;

export type AppBrand = typeof APP_BRAND;

export function formatAppTitle(section?: string): string {
  if (!section?.trim()) {
    return APP_BRAND.windowTitle;
  }

  return `${section.trim()} - ${APP_BRAND.windowTitle}`;
}
