// This file is generated by scripts/sync-template-config.mjs.
// Do not edit it manually.

export const TEMPLATE_CONFIG = {
  appName: "Desktop Shell",
  packageName: "desktop-shell",
  productName: "Desktop Shell",
  identifier: "com.example.desktop-shell",
  description: "A minimal Tauri React desktop shell.",
  repositoryUrl: "https://github.com/example/desktop-shell",
  deepLinkScheme: "desktop-shell",
  updaterEndpoint:
    "https://github.com/example/desktop-shell/releases/latest/download/latest.json",
} as const;

export type TemplateConfig = typeof TEMPLATE_CONFIG;
