// This file is generated by scripts/sync-template-config.mjs.
// Do not edit it manually.

export const TEMPLATE_CONFIG = {
  appName: "Tunnel MCP",
  packageName: "tunnel-mcp",
  productName: "Tunnel MCP",
  identifier: "com.baicie.tunnel-mcp",
  description: "Local MCP gateway desktop client.",
  repositoryUrl: "https://github.com/baicie/tunnel-mcp",
  deepLinkScheme: "tunnel-mcp",
  updaterEndpoint:
    "https://github.com/baicie/tunnel-mcp/releases/latest/download/latest.json",
} as const;

export type TemplateConfig = typeof TEMPLATE_CONFIG;
