// This file is generated by scripts/sync-template-config.mjs.
// Do not edit it manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AppBrand {
    pub app_name: &'static str,
    pub package_name: &'static str,
    pub product_name: &'static str,
    pub description: &'static str,
    pub identifier: &'static str,
    pub repository_url: &'static str,
    pub deep_link_scheme: &'static str,
    pub updater_endpoint: &'static str,
    pub config_dir_name: &'static str,
    pub settings_file_name: &'static str,
    pub database_file_name: &'static str,
    pub log_file_name: &'static str,
    pub tray_tooltip: &'static str,
    pub window_title: &'static str,
}

pub const APP_BRAND: AppBrand = AppBrand {
    app_name: "Desktop Shell",
    package_name: "desktop-shell",
    product_name: "Desktop Shell",
    description: "A minimal Tauri React desktop shell.",
    identifier: "com.example.desktop-shell",
    repository_url: "https://github.com/example/desktop-shell",
    deep_link_scheme: "desktop-shell",
    updater_endpoint:
        "https://github.com/example/desktop-shell/releases/latest/download/latest.json",
    config_dir_name: "desktop-shell",
    settings_file_name: "shell-settings.json",
    database_file_name: "desktop-shell.db",
    log_file_name: "desktop-shell.log",
    tray_tooltip: "Desktop Shell",
    window_title: "Desktop Shell",
};

pub fn app_title(section: Option<&str>) -> String {
    match section {
        Some(section) if !section.trim().is_empty() => {
            format!("{} - {}", section.trim(), APP_BRAND.window_title)
        }
        _ => APP_BRAND.window_title.to_string(),
    }
}

pub fn brand_values() -> Vec<&'static str> {
    vec![
        APP_BRAND.app_name,
        APP_BRAND.package_name,
        APP_BRAND.product_name,
        APP_BRAND.description,
        APP_BRAND.identifier,
        APP_BRAND.repository_url,
        APP_BRAND.deep_link_scheme,
        APP_BRAND.updater_endpoint,
        APP_BRAND.config_dir_name,
        APP_BRAND.settings_file_name,
        APP_BRAND.database_file_name,
        APP_BRAND.log_file_name,
        APP_BRAND.tray_tooltip,
        APP_BRAND.window_title,
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn brand_should_have_required_identity() {
        assert!(!APP_BRAND.app_name.is_empty());
        assert!(!APP_BRAND.package_name.is_empty());
        assert!(!APP_BRAND.identifier.is_empty());
        assert!(!APP_BRAND.repository_url.is_empty());
        assert!(!APP_BRAND.updater_endpoint.is_empty());
    }

    #[test]
    fn app_title_should_format_section() {
        assert_eq!(app_title(None), APP_BRAND.window_title);
        assert_eq!(
            app_title(Some("Settings")),
            format!("Settings - {}", APP_BRAND.window_title)
        );
    }
}
